all: wordsearch.exe wordgen.exe pager.exe launcher.exe

wordsearch.exe: wordsearch.c
	gcc wordsearch.c -o wordsearch.exe
wordgen.exe: wordgen.c
	gcc wordgen.c -o wordgen.exe
pager.exe: pager.c
	gcc pager.c -o pager.exe
launcher.exe: launcher.c
	gcc launcher.c -o launcher.exe